namespace Avalonia.Win32.Interop.Automation;

internal enum UiaEventId
{
	ToolTipOpened = 20000,
	ToolTipClosed,
	StructureChanged,
	MenuOpened,
	AutomationPropertyChanged,
	AutomationFocusChanged,
	AsyncContentLoaded,
	MenuClosed,
	LayoutInvalidated,
	Invoke_Invoked,
	SelectionItem_ElementAddedToSelection,
	SelectionItem_ElementRemovedFromSelection,
	SelectionItem_ElementSelected,
	Selection_Invalidated,
	Text_TextSelectionChanged,
	Text_TextChanged,
	Window_WindowOpened,
	Window_WindowClosed,
	MenuModeStart,
	MenuModeEnd,
	InputReachedTarget,
	InputReachedOtherElement,
	InputDiscarded,
	SystemAlert,
	LiveRegionChanged,
	HostedFragmentRootsInvalidated,
	Drag_DragStart,
	Drag_DragCancel,
	Drag_DragComplete,
	DropTarget_DragEnter,
	DropTarget_DragLeave,
	DropTarget_Dropped,
	TextEdit_TextChanged,
	TextEdit_ConversionTargetChanged,
	Changes
}
