namespace Avalonia.Win32.DirectX;

internal enum D3D_DRIVER_TYPE
{
	D3D_DRIVER_TYPE_UNKNOWN,
	D3D_DRIVER_TYPE_HARDWARE,
	D3D_DRIVER_TYPE_REFERENCE,
	D3D_DRIVER_TYPE_NULL,
	D3D_DRIVER_TYPE_SOFTWARE,
	D3D_DRIVER_TYPE_WARP
}
