namespace Avalonia.Win32.DirectX;

internal enum DXGI_MODE_ROTATION
{
	DXGI_MODE_ROTATION_UNSPECIFIED,
	DXGI_MODE_ROTATION_IDENTITY,
	DXGI_MODE_ROTATION_ROTATE90,
	DXGI_MODE_ROTATION_ROTATE180,
	DXGI_MODE_ROTATION_ROTATE270
}
