using System;

namespace Avalonia.Win32.DirectX;

[Flags]
internal enum DXGI_SWAP_CHAIN_FLAG
{
	DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1,
	DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2,
	DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4,
	DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8,
	DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 0x10,
	DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 0x20,
	DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 0x40,
	DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 0x80,
	DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 0x100,
	DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 0x200,
	DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 0x400,
	DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 0x800,
	DXGI_SWAP_CHAIN_FLAG_RESTRICTED_TO_ALL_HOLOGRAPHIC_DISPLAYS = 0x1000
}
