using System;

namespace LibCpp2IL.MachO;

[Flags]
public enum MachOSectionFlags : uint
{
	TYPE_BITMASK = 0xFFu,
	ATTRIBUTES_BITMASK = 0xFFFFF00u,
	USER_ATTRIBUTES_BITMASK = 0xFF000000u,
	SYSTEM_ATTRIBUTES_BITMASK = 0xFFFF00u,
	TYPE_REGULAR = 0u,
	TYPE_ZEROFILL = 1u,
	TYPE_CSTRING_LITERALS = 2u,
	TYPE_4BYTE_LITERALS = 3u,
	TYPE_8BYTE_LITERALS = 4u,
	TYPE_LITERAL_POINTERS = 5u,
	TYPE_NON_LAZY_SYMBOL_POINTERS = 6u,
	TYPE_LAZY_SYMBOL_POINTERS = 7u,
	TYPE_SYMBOL_STUBS = 8u,
	TYPE_MOD_INIT_FUNC_POINTERS = 9u,
	TYPE_MOD_TERM_FUNC_POINTERS = 0xAu,
	TYPE_COALESCED = 0xBu,
	TYPE_GB_ZEROFILL = 0xCu,
	TYPE_INTERPOSING = 0xDu,
	TYPE_16BYTE_LITERALS = 0xEu,
	TYPE_DTRACE_DOF = 0xFu,
	TYPE_LAZY_DYLIB_SYMBOL_POINTERS = 0x10u,
	TYPE_THREAD_LOCAL_REGULAR = 0x11u,
	TYPE_THREAD_LOCAL_ZEROFILL = 0x12u,
	TYPE_THREAD_LOCAL_VARIABLES = 0x13u,
	TYPE_THREAD_LOCAL_VARIABLE_POINTERS = 0x14u,
	TYPE_THREAD_LOCAL_INIT_FUNCTION_POINTERS = 0x15u,
	TYPE_INIT_FUNC_OFFSETS = 0x16u,
	ATTR_PURE_INSTRUCTIONS = 0x80000000u,
	ATTR_NO_TOC = 0x40000000u,
	ATTR_STRIP_STATIC_SYMS = 0x20000000u,
	ATTR_NO_DEAD_STRIP = 0x10000000u,
	ATTR_LIVE_SUPPORT = 0x8000000u,
	ATTR_SELF_MODIFYING_CODE = 0x4000000u,
	ATTR_DEBUG = 0x2000000u,
	ATTR_SOME_INSTRUCTIONS = 0x400u,
	ATTR_EXT_RELOC = 0x200u,
	ATTR_LOC_RELOC = 0x100u
}
